services:
  stats-server:
    build: stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stats

  ewm-service:
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
